/** Original challenges. Reference metadata is not a redistribution of Moodle materials. */
export const SOURCES = {
  sets: { title: 'J. Krcum — Skupovi. Skupovi brojeva', location: 'PDF pp. 1–5: membership, union, intersection, difference, complement; exercises on p. 5.', note: 'Reviewed from the supplied course pack. This chapter covers set operations, not the full algebra course.' },
  python: { title: 'Toma Rončević — Uvod u programiranje (6 January 2016)', location: '§2.3; §3.1–3.2; §3.4. Printed pp. 29–32, 45–51, 56–65 (PDF page = printed page + 1).', note: 'The source uses Python 2. All executable exercises here use Python 3: print(...), / versus //, and no Python 2 input evaluation.' },
  web: { title: 'Osnove izrade web stranica — Predavanje 13.10. (13 October 2021)', location: 'PDF pp. 1–8: document structure/headings; 17–18: links/anchors; 19–24: CSS, selectors and colours.', note: 'Reviewed from the supplied lecture. We use modern id-based anchors and quoted attributes. Preview checks are deliberately limited, not a full HTML/accessibility audit.' }
};
export const ISLANDS = [
  { id:'sets', name:'The Firefly Glade', course:'Linearna algebra', tag:'Sets / skupovi', x:.25, y:.43, colour:'#bfe5ae', symbol:'∩', intro:'Two moonflowers claim the same fireflies. Neither flower is willing to share. Fortunately, mathematics is less petty.', reward:'The green lantern', source:'sets' },
  { id:'python', name:'The Clockwork Orchard', course:'Uvod u programiranje', tag:'Python / programiranje', x:.70, y:.32, colour:'#ffc98b', symbol:'{ }', intro:'Pip is a mechanical moth with magnificent wings and absolutely no judgement. Your code becomes its instincts.', reward:'The amber lantern', source:'python' },
  { id:'web', name:'The Paper Observatory', course:'Osnove izrade web stranica', tag:'HTML + CSS / web', x:.70, y:.73, colour:'#c9baff', symbol:'</>', intro:'The constellations have lost their labels. Build a tiny page the wandering stars can actually navigate.', reward:'The violet lantern', source:'web' },
  { id:'digital', name:'The Sleeping Foundry', course:'Digitalni sustavi', tag:'Materials pending', x:.16, y:.79, colour:'#6e7f94', symbol:'◇', pending:true, intro:'No invented course pack here. This island opens after the real Digitalni sustavi materials are reviewed.' },
  { id:'computing', name:'The Unwritten Archive', course:'Uvod u računarstvo', tag:'Materials pending', x:.87, y:.55, colour:'#6e7f94', symbol:'?', pending:true, intro:'The official course outline is not a substitute for the teaching materials. This island is reserved for a later update.' }
];
export const LESSONS = [
  { id:'set-union', island:'sets', kind:'sets', op:'union', title:'A rather inclusive invitation', term:'Unija · A ∪ B',
    story:'The first lantern welcomes every firefly belonging to flower A, flower B, or both. Select its guests and release them.',
    learn:'A set is a collection of distinct elements. A ∪ B contains anything in A OR in B, including elements in both. The same element is never counted twice.',
    example:'If A = {2, 5} and B = {5, 9}, then A ∪ B = {2, 5, 9}.',
    hints:['“Or” includes the overlap. Start with every member of A.', 'Add the members of B that are not already selected. Leave out fireflies in neither set.'] },
  { id:'set-intersection', island:'sets', kind:'sets', op:'intersection', title:'The extremely exclusive picnic', term:'Presjek · A ∩ B',
    story:'These two flowers will host a picnic only for fireflies they both know. Invite the shared members. The others will cope.',
    learn:'A ∩ B contains an element only when it belongs to A AND to B. Membership in just one set is not enough. The intersection can be empty.',
    example:'If A = {1, 6} and B = {6, 8}, then A ∩ B = {6}.',
    hints:['A selected firefly must carry both the A and B membership badges.', 'Do not include an element merely because it appears somewhere in the diagram.'] },
  { id:'set-difference', island:'sets', kind:'sets', op:'difference', title:'The flower with a grudge', term:'Razlika · A ∖ B',
    story:'Flower A wants its own fireflies, but none that also visit B. An unnecessarily dramatic way to demonstrate set difference.',
    learn:'A ∖ B contains elements in A but NOT in B. Direction matters: A ∖ B is generally different from B ∖ A.',
    example:'If A = {3, 4, 7} and B = {4, 8}, then A ∖ B = {3, 7}.',
    hints:['Start with A, not with every firefly.', 'Remove every member of A that is also in B.'] },
  { id:'set-complement', island:'sets', kind:'sets', op:'complement', title:'Everybody else', term:'Komplement · Aᶜ relative to U',
    story:'The final lantern belongs to the outsiders: every firefly in this glade that does not belong to A.',
    learn:'Aᶜ = U ∖ A. The universal set U defines what “everything else” means. Members of B can belong to Aᶜ, but only if they are not in A.',
    example:'For U = {1, 2, 3, 4} and A = {2, 4}, Aᶜ = {1, 3}. Changing U can change the complement.',
    hints:['Use the displayed U. Do not add numbers that are not in it.', 'Select the B-only region AND the region outside both flowers.'] },
  { id:'py-energy', island:'python', kind:'python', title:'Breakfast for a mechanical moth', term:'Varijable i izrazi · variables and expressions', output:'energy',
    story:'Each nectar pod gives Pip 3 units of energy. A leak takes some away. Give Pip the correct energy so it can light the orchard.',
    learn:'A variable gives a value a name. Assignment (=) stores the result of an expression. Multiplication uses *. The test runner supplies pods and leak; calculate energy from those inputs rather than hard-coding one answer.',
    example:'A different example: coins = bags * 5 - spent. With bags = 3 and spent = 4, coins becomes 11.',
    starter:'# pods and leak are already provided.\n# Each pod is worth 3; subtract the leak.\nenergy = 0\n',
    hints:['Translate “3 for each pod” into multiplication.', 'Use both supplied input variables in the expression assigned to energy.'] },
  { id:'py-decision', island:'python', kind:'python', title:'Pip discovers self-preservation', term:'Odluke · if / else and Boolean conditions', output:'fly',
    story:'Pip should fly only when charged is True AND wind is strictly below the displayed limit. Otherwise it should stay on its very comfortable leaf.',
    learn:'An if statement chooses whether to execute an indented block. A colon starts that block. and requires both conditions; < is strictly less than (not less than or equal). fly must be the Boolean True or False, not text.',
    example:'Different example:\nopen_door = False\nif has_key and hour < 20:\n    open_door = True',
    starter:'# wind, limit and charged are supplied.\n# Store a Boolean in fly.\nfly = False\n',
    hints:['Test both charged and wind < limit. The boundary wind == limit must not fly.', 'An if/else solution or a Boolean expression can both work. True and False start with capitals.'] },
  { id:'py-loop', island:'python', kind:'python', title:'One more lantern, one more time', term:'Petlje · loops and an accumulator', output:'charge', requiresLoop:true,
    story:'The lanterns cost 1, then 2, then 3 energy units, and so on up to stops. Use a loop to add their costs. Pip will follow the lights you can afford.',
    learn:'An accumulator starts at an initial value and changes each iteration. With while, update the counter so the condition eventually becomes false. Here add every integer from 1 through stops, inclusive. With stops = 0, no iterations are needed.',
    example:'Different example:\ntotal = 0\ni = 1\nwhile i <= 3:\n    total = total + 2\n    i = i + 1\n# total is 6. Each iteration adds 2.',
    starter:'# stops is supplied. Use a while or for loop.\ncharge = 0\nstep = 1\n',
    hints:['Repeat while step <= stops. Add step to charge, not a fixed value.', 'Increase step inside the loop. Stops of 0 and 1 are useful boundary tests.'] },
  { id:'web-structure', island:'web', kind:'web', title:'A name for the nameless sky', term:'HTML · title, headings and paragraphs',
    story:'Create the observatory’s welcome page. Give it a browser title, a visible main heading, and a real paragraph telling visitors what they have found.',
    learn:'HTML describes structure. <title> names the browser tab; <h1> is the visible main heading; <p> marks a paragraph. Put metadata in <head> and visible content in <body>. Closing tags matter.',
    example:'<h1>A different little island</h1>\n<p>A place to rest before the journey.</p>',
    hints:['A title belongs inside head. A visible heading belongs inside body.', 'Use one h1 and at least one non-empty p. A giant styled paragraph is not an h1.'] },
  { id:'web-links', island:'web', kind:'web', title:'Directions for a lost constellation', term:'Poveznice i sidrišta · links and anchors',
    story:'Stars are terrible at scrolling. Build a text link that jumps to the named destination section on your page.',
    learn:'An anchor link uses href="#destination". The target element needs the matching id="destination". The # belongs in href, not in the id. A visible link needs meaningful text.',
    example:'<a href="#harbour">Go to the harbour</a>\n<h2 id="harbour">Harbour</h2>',
    hints:['Use the exact destination ID given in the task, with # only in href.', 'Check that the destination ID occurs once and that the link has text.'] },
  { id:'web-css', island:'web', kind:'web', title:'Turn the observatory on', term:'CSS · class selectors, colour and spacing',
    story:'The observatory has two paper beacons. Give BOTH the requested colour and some breathing room with a reusable CSS class.',
    learn:'A CSS rule has a selector and declarations: .note { color: gold; padding: 16px; }. A dot targets a class; a # targets an id. Multiple elements can share a class. Use the CSS editor, not inline style, for this task.',
    example:'.message {\n    color: navy;\n    padding: 12px;\n}',
    hints:['Your selector must match the class on both beacon paragraphs.', 'Set color and padding. The checker inspects computed styles on both elements, not just whether words occur in your code.'] }
].map(lesson => ({ ...lesson, source:lesson.island }));
export const lessonById = id => LESSONS.find(l => l.id === id);
export const islandLessons = id => LESSONS.filter(l => l.island === id);
