/** Original teaching for the shared systems. Track order is not campaign order. */
export const STATIONS=[
 {id:'web',name:'Information terminal',subject:'HTML & CSS',symbol:'</>',person:'Nova',x:.70,y:.30,
  purpose:'Your actual page tells visitors where to send a delivery. This is the same page you keep in the Paper Observatory.',
  lessons:[
   {title:'What is a page?',text:'A browser is the program displaying this game. HTML is text that describes the structure of a page. The browser reads that source and draws the result. An element combines an opening tag, content and a closing tag. <h1> begins the main heading; </h1> ends it. The slash / means “close”. <p> and </p> mark a paragraph, a block of ordinary text.',example:'<h1>The little reading room</h1>\n<p>A quiet place for a book.</p>',try:'Type a name into the label press and make a heading. Then add a paragraph telling visitors to go north. Inspect the HTML it creates; these are real elements, not an image.'},
   {title:'Your page, in the harbour',text:'You can change the source directly. Keep angle brackets < > around tag names, not around ordinary sentences. A browser tab title is different from a visible h1 heading. Our fictional visitor follows a simple published rule: find a relevant link, or read the first visible paragraph. That text must contain exactly one direction word, north or west. This is a game rule, not something HTML does automatically.',example:'<h1>Garden guide</h1>\n<p>Walk west to find the garden.</p>',try:'Change the direction in your page and watch Nova’s route change. A well-formed page can still give the wrong directions!'},
   {title:'One terminal, several destinations',text:'A link uses an a element. An attribute is extra information in its opening tag. href="#garden" points within this page to the unique element with id="garden". The # goes in href, not in id. The visitor looks for a label containing “chart” for the Observatory or “garden” for the garden. CSS changes appearance, not which destination a link names. The full workshop explains document frames, classes, selectors and spacing from the beginning.',example:'<a href="#garden">Garden directions</a>\n<section id="garden">\n  <h2>Garden</h2>\n  <p>Take the west path.</p>\n</section>',try:'Keep the first page, then add another route rather than replacing the whole page. Open the full Observatory workbench for guided links and CSS.'}
  ]},
 {id:'sets',name:'Cargo yard',subject:'Mathematics',symbol:'∪',person:'Orin',x:.28,y:.66,
  purpose:'The very same crates you sort here become Pip’s load. Their membership badges stay visible on the map.',
  lessons:[
   {title:'A set is a group',text:'A set is a collection of distinct things. Each thing is called an element or member. Here our four crates are the universe U: all the items being considered. A is the set of fragile crates; B is the set of survey crates. One crate can belong to both. Curly braces list members: {lens, lantern}. Order does not matter, and listing an item twice does not create another member.',example:'A = {lens, lantern}\nB = {lens, chart}\nlens ∈ A means “lens belongs to A”.\nchart ∉ A means “chart does not belong to A”.',try:'Inspect a crate’s A and B badges. Click crates to put them on the loading tray. Start with the survey kit B for Nova, or choose another request.'},
   {title:'Combining groups',text:'A ∪ B (union / unija) includes members of A OR B, including both. A ∩ B (intersection / presjek) includes only members shared by both. A ∖ B (difference / razlika) keeps members of A that are NOT in B. Direction matters: A ∖ B usually differs from B ∖ A. Complement means everything in the chosen universe that is NOT in A.',example:'For X = {1, 2} and Y = {2, 3}:\nX ∪ Y = {1, 2, 3}\nX ∩ Y = {2}\nX ∖ Y = {1}',try:'Try a sorter rule and watch which physical crates enter the tray. Inspect why the lens does, or does not, pass each rule.'},
   {title:'Use the rule, not the picture',text:'A sorter applies membership tests to every crate. Choosing a rule is not submitting an answer: the resulting cargo really changes, even if it is wrong for this request. A∪B does not mean add the two counts; the shared lens belongs in the load only once. When cargo changes, the computer’s previously scanned list is out of date. Scan it again before dispatch.',example:'To find A ∖ B:\n1. Start with every member of A.\n2. Remove anything also in B.\n3. Keep the remaining members.',try:'Switch between Nova’s B request, Mira’s A∖B request and Orin’s A∪B request. Reuse the same yard and keep your other systems.'}
  ]},
 {id:'python',name:'Pip’s charger',subject:'Programming',symbol:'{ }',person:'Pip',x:.47,y:.47,
  purpose:'Your Python output is the actual battery level. Pip uses it to lift the selected crates and cross the route.',
  lessons:[
   {title:'Names and values',text:'A value is a piece of information, such as the number 5. A variable gives a value a name. In Python, energy = 5 stores 5 under the name energy. The = here is assignment, not a question asking whether two values are equal. An expression such as 2 + 3 calculates a value first. A line starting with # is a comment for people; Python does not run it.',example:'batteries = 2\ncharge = batteries + 3\n# charge now holds 5',try:'Replace the 0 in energy = 0 with a small number and run the charger. Observe Pip’s battery, then try an expression such as 2 + 3.'},
   {title:'Calculate from the inputs',text:'The game supplies pods and leak as input variables. One pod contains 3 energy units; the leak removes units. Python uses * for multiplication and - for subtraction. Multiplication is calculated before subtraction. Rather than typing the answer for one situation, write an expression using the input names. The battery can hold at most 12 units; lifting each selected crate costs 1 and each route segment costs 1.',example:'Different machine: each pack holds 2 units.\npower = packs * 2 - loss\n# packs=4, loss=1 gives 8-1 = 7',try:'Write your energy calculation. Change pods or leak and rerun without changing the program. Does it still produce the intended amount?'},
   {title:'Read what actually happened',text:'A program is a sequence of instructions. The trace shows values before each line executes, then the final state. A Python error is information, not a penalty. Names must be spelled consistently: Energy and energy are different. This local introductory runner executes real Python, but deliberately disables imports, files, attributes and other advanced features. Its allowed functions and limits are documented in the game’s technical notes.',example:'energy = pods * 3\nenergy = energy - leak\n# The second assignment updates the same variable.',try:'Compare a one-line and a two-line calculation. Dispatch a heavier load or reduce the pod count to see why inspecting the inputs matters.'}
  ]},
 {id:'digital',name:'Channel signal',subject:'Digital systems',symbol:'&',person:'Mira',x:.60,y:.72,
  purpose:'Your circuit decides whether Pip receives a departure signal. Its inputs come from the actual cargo and channel.',
  lessons:[
   {title:'Two signal states',text:'This model uses two states: 0 means off/false, and 1 means on/true. An input is a signal entering a device; an output is what leaves it. Our loaded input is 1 when the tray contains any crate. Our clear input is 1 when the channel is open. Neither says that the cargo is the correct set—that is a different question.',example:'loaded = 1: something is on the tray\nclear = 0: the channel is blocked\noutput = 0: Pip is told to wait',try:'Toggle the channel and select or remove cargo. Watch the two real input lamps before choosing a gate.'},
   {title:'AND and OR are different',text:'An AND gate outputs 1 only when both inputs are 1. An OR gate outputs 1 when at least one input is 1, including both. NOT flips a single input: 0 becomes 1 and 1 becomes 0. A truth table lists every combination of inputs and the resulting output. Here we want departure only when loaded AND clear.',example:'loaded clear | AND OR\n   0     0   |  0   0\n   0     1   |  0   1\n   1     0   |  0   1\n   1     1   |  1   1',try:'Try OR with a loaded tray and a blocked channel. The output really turns on. Pip then encounters the barrier rather than magically passing it.'},
   {title:'Test the boundary cases',text:'One successful departure does not show that a circuit is suitable for every state. AND and OR agree when both inputs are 1. The difference appears when only one is 1. The table below evaluates your chosen circuit for all four combinations, separately from the real channel. This is an introductory signal model, not a full electronics simulator.',example:'Test an empty tray with a clear channel.\nThen test a loaded tray with a blocked channel.\nA safe departure rule keeps the output at 0 in both.',try:'Choose a gate by reasoning about all four rows. Toggle the real channel again and see how the same circuit responds.'}
  ]},
 {id:'computing',name:'Manifest computer',subject:'Computing',symbol:'▤',person:'Orin',x:.28,y:.30,
  purpose:'This computer reads the selected crate IDs and produces the manifest Pip checks before leaving.',
  lessons:[
   {title:'Input → processing → output',text:'Input is information entering a computer. Here the scanner reads crate IDs. Processing works on that input; our simplified processor turns the readings into a manifest, a list of cargo. Output makes a result available, here on a display. A screen is not the processor. The cable controls below model these jobs, not the physical plugs inside a real computer.',example:'Scanner: lens, chart\nProcessor: make a list of those IDs\nDisplay: “Glass lens; Sky chart”',try:'Connect Scanner → Processor and Processor → Display, then scan the tray. Changing a cable changes where the information goes.'},
   {title:'Working information and storage',text:'The display in this model shows a current working result. Storage keeps a copy for later recall. Switching the fictional computer off clears its display but leaves stored data. That is a model of volatile versus persistent information—not a claim that a physical monitor stores a program. Your browser separately saves the whole game so you can continue after closing it.',example:'Scan → display\nStore → keep a copy\nPower off → clear the working display\nRecall → load the stored copy',try:'Store a manifest, switch this computer off, then recall it. Try once without storing a copy and compare the outcomes.'},
   {title:'Correct data can become stale',text:'A stored list describes the crates that were scanned at that moment. If you change the tray afterwards, the earlier manifest no longer describes the current load. Pip compares the displayed list with the actual tray before dispatch. Storage is useful, but an old result is not automatically a current result.',example:'Stored: {lens, chart}\nTray after editing: {lantern}\nThese describe different loads. Rescan.',try:'Change the cargo after scanning and try a dispatch. Trace the old data back to its source, then update it rather than changing unrelated code.'}
  ]}
];
export const stationById=id=>STATIONS.find(s=>s.id===id)||STATIONS[0];
