/** Original guided instruction, not redistributed course text.
 * Traceable sections and adaptations: docs/CURRICULUM.md.
 * Demo traces are fixed worked examples, not a replacement Python interpreter.
 */
const say=(title,text,extra={})=>({title,text,...extra});
const ask=(title,text,question,extra={})=>({title,text,question,...extra});
const number=(prompt,answer,why,wrong)=>({type:'number',prompt,answer,why,wrong});
const choice=(prompt,answer,options,why,wrong)=>({type:'choice',prompt,answer,options,why,wrong});
const token=(prompt,answer,why,wrong)=>({type:'text',prompt,answer,why,wrong});
const collection=(prompt,answer,values,why,wrong)=>({type:'set',prompt,answer,values,why,wrong});
const board={U:[1,2,3,4],A:[1,2],B:[2,3]};
const setRules={
  union:{name:'Unija / union',symbol:'A ∪ B',rule:'Keep an element when it is in A OR B. Being in both is also enough.',keep:[1,2,3],reason:['1 is in A. One membership is enough: keep it.','2 is in both. Union includes the overlap, but writes 2 just once.','3 is in B. One membership is enough: keep it.','4 is in neither. It has no invitation: leave it out.'],mini:[4,5,7],prompt:'Now A = {4, 5} and B = {5, 7}. Select their union.',why:'4 belongs to A, 5 belongs to both, and 7 belongs to B. All three belong to the union. 8 is in neither.'},
  intersection:{name:'Presjek / intersection',symbol:'A ∩ B',rule:'Keep an element only when it is in A AND in B. It needs both memberships.',keep:[2],reason:['1 is in A but not B. Only one membership: leave it out.','2 is in both A and B. Both requirements are satisfied: keep it.','3 is in B but not A. Only one membership: leave it out.','4 is in neither. It cannot be in their intersection.'],mini:[5],prompt:'Now A = {4, 5} and B = {5, 7}. Select their intersection.',why:'Only 5 occurs in both lists. 4 and 7 each occur in just one; 8 occurs in neither.'},
  difference:{name:'Razlika / difference',symbol:'A ∖ B',rule:'Start with A. Keep an element only if it is NOT also in B. The left-hand set is the starting set.',keep:[1],reason:['1 is in A and not in B. Keep it.','2 is in A, but is also in B. Remove it from the result.','3 is not in A. Do not add it merely because it is in B.','4 is not in A. It never entered the starting collection.'],mini:[4],prompt:'Now A = {4, 5} and B = {5, 7}. Select A ∖ B (not B ∖ A).',why:'Start with {4, 5}. Remove 5 because it also belongs to B. That leaves {4}. 7 would belong to B ∖ A, the other direction.'},
  complement:{name:'Komplement / complement',symbol:'Aᶜ',rule:'Start with the universal set U: everything considered in this question. Keep the elements of U that are NOT in A.',keep:[3,4],reason:['1 is in A, so it is not in the complement of A.','2 is in A, even though it is also in B. Leave it out.','3 is in U and not A. It belongs to the complement, even though it is in B.','4 is in U and not A. Being outside both circles does not exclude it from U.'],mini:[7,8],prompt:'Now U = {4, 5, 7, 8} and A = {4, 5}. Select Aᶜ relative to this U.',why:'From U, remove 4 and 5 because they are in A. Both 7 and 8 remain. Numbers not in U are not candidates.'}
};
function setGuide(op){
  const r=setRules[op];
  return {source:'LA-01 · pp. 1–4; worked practice p. 5. The small examples here are original.',steps:[
    say('First, what is a set?','A set (skup) is a collection of elements (elementi). A = {1, 2} means that the collection named A contains 1 and 2. The braces { } enclose the members; commas separate them. U names all the elements considered here; A and B are smaller collections within U.',{board}),
    ask('Read one membership','The symbol ∈ means “is an element of”. Its crossed-out version ∉ means “is not an element of”. The same numbered firefly can belong to two collections; it is still one firefly.',choice('Look at A = {1, 2}. Is 2 ∈ A true?','yes',[['yes','Yes — 2 is in A'],['no','No — 2 is not in A']],'Yes. You can find 2 in the list {1, 2}. That is all membership asks.','Look for the number 2 inside the braces naming A. You do not need to calculate anything.'),{board}),
    say(r.name,r.rule+' The operation creates a result; it does not change the original A or B.',{code:r.symbol,board,frames:[
      {focus:1,result:r.keep.filter(n=>n<=1),caption:r.reason[0]},
      {focus:2,result:r.keep.filter(n=>n<=2),caption:r.reason[1]},
      {focus:3,result:r.keep.filter(n=>n<=3),caption:r.reason[2]},
      {focus:4,result:r.keep,caption:r.reason[3]}
    ]}),
    ask('Make just one decision',r.rule,choice('For A = {1, 2}, B = {2, 3}, U = {1, 2, 3, 4}: should 2 enter '+r.symbol+'?',r.keep.includes(2)?'yes':'no',[['yes','Include 2'],['no','Leave 2 out']],r.reason[1],r.reason[1]),{board}),
    ask('Now you assemble a small result','Click the numbered tokens you need. Click a selected token again to remove it. You may leave all tokens unselected when the result is empty.',collection(r.prompt,r.mini,[4,5,7,8],r.why,r.why)),
    say('A method you can use without the flowers','Read the operation. Check one candidate at a time against its membership rule. Write the accepted elements inside braces. An empty result is written {} or ∅. In the experiment, the firefly labels tell you which sets it belongs to.',{code:r.symbol+'\n'+r.rule,recap:true})
  ]};
}
const energyCode='pods = 4\nleak = 2\nenergy = pods * 3 - leak';
const decisionCode='fly = False\nif charged and wind < limit:\n    fly = True';
export const LOOP_DEMO_CODE='charge = 0\nstep = 1\nwhile step <= stops:\n    charge = charge + step\n    step = step + 1';
export const LOOP_DEMO_FRAMES=[
  {line:1,values:{stops:3,charge:0},caption:'Start the running total (charge) at 0. Nothing has been added yet.'},
  {line:2,values:{stops:3,charge:0,step:1},caption:'step names the next cost. Start with the first cost, 1.'},
  {line:3,values:{stops:3,charge:0,step:1},caption:'Check 1 <= 3. True, so enter the indented body.'},
  {line:4,values:{stops:3,charge:1,step:1},caption:'Evaluate charge + step using the old values: 0 + 1 = 1. Store 1 in charge.'},
  {line:5,values:{stops:3,charge:1,step:2},caption:'Increase step: 1 + 1 = 2. The next cost is now 2. Return to the condition.'},
  {line:3,values:{stops:3,charge:1,step:2},caption:'Check 2 <= 3. True. Repeat the body with these NEW values.'},
  {line:4,values:{stops:3,charge:3,step:2},caption:'Add the second cost: 1 + 2 = 3. charge now remembers 3.'},
  {line:5,values:{stops:3,charge:3,step:3},caption:'Increase step to 3, ready for the third cost.'},
  {line:3,values:{stops:3,charge:3,step:3},caption:'Check 3 <= 3. True: “less than OR equal” includes the final cost.'},
  {line:4,values:{stops:3,charge:6,step:3},caption:'Add the third cost: 3 + 3 = 6. charge now remembers 6.'},
  {line:5,values:{stops:3,charge:6,step:4},caption:'Increase step to 4. We have already added costs 1, 2 and 3.'},
  {line:3,values:{stops:3,charge:6,step:4},caption:'Check 4 <= 3. False. Skip the body and finish. The result is charge = 6.'}
];
export const GUIDES={
 'set-union':setGuide('union'), 'set-intersection':setGuide('intersection'), 'set-difference':setGuide('difference'), 'set-complement':setGuide('complement'),
 'py-energy':{source:'UP-01 · §2.3 (printed pp. 29–32), §3.1–3.2. Original examples, executed/checked as Python 3.',steps:[
  say('Pip needs instructions, not a guessed number','A program is a sequence of instructions. First we will read a few values and make one calculation. There is no need to know loops or functions yet. In the example, Pip has 4 pods, each worth 3 energy; a leak loses 2.'),
  say('Give a value a name','A variable (varijabla) is a name for a value. In pods = 4, pods is the name, 4 is the value, and = assigns that value to the name. Later, using pods in a calculation uses its current value. This is assignment, not a question about equality.',{code:'pods = 4\nleak = 2',values:{pods:4,leak:2}}),
  ask('Multiply before subtracting','Python uses * for multiplication and - for subtraction. Four pods worth 3 each give 4 * 3 = 12. The leak has not been subtracted yet.',number('With pods = 5, what is pods * 3? Type the number.',15,'5 pods × 3 units each = 15. The same expression adapts when pods changes.','Count 3 for each of 5 pods: 3 + 3 + 3 + 3 + 3.'),{code:'pods * 3'}),
  say('Watch a complete calculation','Read the right-hand side first, calculate it, then assign the result to the name on the left. Step through the example; the cards show values AFTER the highlighted instruction.',{code:energyCode,frames:[
   {line:1,values:{pods:4},caption:'pods = 4 gives the name pods the value 4.'},
   {line:2,values:{pods:4,leak:2},caption:'leak = 2 gives the name leak the value 2. pods stays 4.'},
   {line:3,values:{pods:4,leak:2,energy:10},caption:'Read pods * 3 - leak as 4 * 3 - 2. Multiply to get 12; subtract 2 to get 10; assign 10 to energy.'}
  ]}),
  ask('Choose the missing instruction','The game will give you pods and leak. You write the calculation; do not replace the supplied values with the example numbers.',choice('Complete: energy = pods __ 3 - leak','*',[['+','+ (add)'],['*','* (multiply)'],['=','= (assign)']],'* expresses “3 for each pod”. The = at the start stores the final result in energy.','Adding 3 once is not the same as getting 3 for every pod. The operation between pods and 3 must be multiplication.'),{code:'energy = pods __ 3 - leak'}),
  ask('Follow it on a new input','Keep the same rule: three units per pod, then subtract the leak.',number('If pods = 2 and leak = 1, what value is assigned to energy?',5,'First 2 * 3 = 6, then 6 - 1 = 5. The instruction stays the same; only the input values change.','Start with two lots of three (6). Then subtract the one unit lost.'),{code:'energy = pods * 3 - leak'}),
  say('Your first program can be one line','In the experiment, replace energy = 0 with your calculation. Lines beginning # are comments for you; Python ignores them. The inputs are supplied before your code runs. You do not need print: this game reads the variable energy. Run experiment tests the same code with several inputs, including zero.',{code:'energy = pods * 3 - leak',recap:true})
 ]},
 'py-decision':{source:'UP-01 · §2.3 (comparisons/Boolean operators), §3.3–3.4 (blocks and decisions). Original Python 3 examples.',steps:[
  say('A decision has two possible answers','A Boolean value is True or False: Python’s values for yes and no. They start with capital letters and have no quotes. Here charged tells us whether Pip has power. fly is the answer we must produce.',{values:{charged:true,fly:false}}),
  say('Compare the wind with a limit','wind < limit asks whether wind is strictly less than limit. < means less than; <= includes equality. A single = assigns; two signs == compare for equality. Our flying rule requires <, not <=.',{code:'wind = 4\nlimit = 5\n# 4 < 5 is True'}),
  ask('Inspect the boundary','If wind is exactly the limit, it is not below the limit.',choice('With wind = 5 and limit = 5, is wind < limit True or False?','False',[['True','True'],['False','False']],'False. Five is equal to five, not less than five. Pip stays put at this boundary.','Read < as “strictly below”. Equality would need <=, but that is not our rule.')),
  say('Combine two requirements','and requires BOTH conditions to be True. It is not enough to have power if the wind is too strong, or calm air with no power.',{table:{headers:['charged','wind < limit','Both with and'],rows:[['True','True','True'],['True','False','False'],['False','True','False'],['False','False','False']]}}),
  say('Watch the branch','if checks its condition. The colon : starts a block. Four spaces before fly = True place that instruction inside the block. With charged = True, wind = 2 and limit = 4, step through what happens.',{code:decisionCode,initial:{charged:true,wind:2,limit:4},frames:[
   {line:1,values:{charged:true,wind:2,limit:4,fly:false},caption:'Start fly at False. Unless we later change it, Pip will stay.'},
   {line:2,values:{charged:true,wind:2,limit:4,fly:false},caption:'True and (2 < 4) is True. Enter the indented block.'},
   {line:3,values:{charged:true,wind:2,limit:4,fly:true},caption:'Assign True to fly. If the condition had been False, this line would be skipped and fly would stay False.'}
  ]}),
  ask('Try only the decision','Both requirements must hold.',choice('charged is False; wind = 1; limit = 4. What should fly be?','False',[['True','True'],['False','False']],'False. The wind is safe, but charged is False. and needs both requirements.','Safe wind is only half the rule. Check charged too.')),
  say('Now give Pip the rule','The three-line version below starts with “stay”, then changes to “fly” when both conditions pass. Write the indented line with four spaces (Tab in the editor inserts them). A one-line Boolean assignment can also work, but is not necessary.',{code:decisionCode,recap:true})
 ]},
 'py-loop':{source:'UP-01 · §3.3–3.4, especially printed pp. 61–65: while, counter, trace table, stopping condition. Original accumulator example.',steps:[
  say('Why a loop?','Suppose the lantern costs are 1, then 2, then 3. Their total is 1 + 2 + 3 = 6. A loop (petlja) repeats a few instructions so the same program can handle three lanterns, seven lanterns, or none. We will build this in small pieces.'),
  say('Two names with different jobs','charge is the running total: begin at 0. step is the NEXT cost to add: begin at 1. stops is supplied by the game and tells you the LAST cost. Do not mix up the total and the next cost.',{code:'charge = 0\nstep = 1',values:{charge:0,step:1,stops:3}}),
  say('Update a running total','charge = charge + step is not a mathematical equation to solve. Read the OLD charge on the right, add step, then store the NEW result on the left. step = step + 1 advances to the next cost.',{code:'charge = charge + step\nstep = step + 1',initial:{charge:0,step:1},frames:[
   {line:1,values:{charge:1,step:1},caption:'Starting from charge = 0 and step = 1: compute 0 + 1, then set charge to 1.'},
   {line:2,values:{charge:1,step:2},caption:'Compute 1 + 1, then set step to 2. The total stays 1.'}
  ]}),
  ask('Add just the next cost','You have already paid cost 1, so charge = 1. The next cost is step = 2.',number('After charge = charge + step, what is charge?',3,'The old charge is 1. Add step, which is 2. The new charge is 3; step is still 2 until another instruction changes it.','Substitute the current values on the right: 1 + 2. Do not replace charge with step alone.')),
  say('Repeat only while there is a cost left','while step <= stops: checks whether the next cost is at most the final cost. The colon starts the block; the indented lines repeat. After the block, Python returns to the condition. If it is False, the body is skipped.',{code:LOOP_DEMO_CODE}),
  say('Walk through every iteration','This is a worked example with stops = 3. Advance at your own pace. Value cards show the state AFTER the highlighted instruction or condition check; these are fixed, verified teaching frames.',{code:LOOP_DEMO_CODE,initial:{stops:3},frames:LOOP_DEMO_FRAMES}),
  ask('Know when to stop','At the top of the loop, the condition is tested before the next addition.',choice('step = 4 and stops = 3. Does while step <= stops enter the body?','no',[['yes','Yes — add another cost'],['no','No — leave the loop']],'No. 4 <= 3 is False. Do not add 4. The total remains 6 for stops = 3.','Substitute the values: is 4 less than OR equal to 3?')),
  ask('Handle an empty journey','For stops = 0, step starts at 1 and the first test 1 <= 0 is False. No cost is added.',number('What value remains in charge?',0,'charge was set to 0 before the loop. The body never ran, so charge stays 0.','Read the starting assignment. A skipped body cannot change its value.')),
  say('Build the loop, then watch your own version','Keep both starting assignments outside the loop. Indent BOTH the addition and the counter update underneath while. If you forget to advance step, the condition can stay True forever. The Stop button and step limit are there for experiments that get stuck.',{code:LOOP_DEMO_CODE,recap:true})
 ]},
 'web-structure':{source:'WEB-01 · pp. 1–3, 7–9: document structure, head/body, headings and paragraphs. Original HTML examples.',steps:[
  say('HTML labels the parts of a page','HTML is markup: it tells the browser what each piece of content is. A tag is an instruction inside angle brackets. In <h1>A quiet sky</h1>, <h1> opens a main heading, the words are its content, and </h1> closes it. The / marks the closing tag.',{code:'<h1>A quiet sky</h1>',html:'<h1>A quiet sky</h1>'}),
  ask('Close the heading','Use the same tag name at both ends. For a paragraph, use p rather than h1.',token('Complete <h1>A quiet sky</____>. Type only the missing tag name.','h1','h1 matches the opening <h1>. The completed element is <h1>A quiet sky</h1>.','The closing tag matches the name in the opening tag. Only the slash is added.'),{code:'<h1>A quiet sky</____>'}),
  say('Two places, two different titles','head contains information about the document. title inside head names the browser tab. body contains visible page content, including h1 and p. A tab title does not create a heading on the page.',{code:'<head>\n  <title>Pip’s notebook</title>\n</head>\n<body>\n  <h1>A quiet sky</h1>\n</body>',html:'<title>Pip’s notebook</title><h1>A quiet sky</h1>'}),
  ask('Choose where readers will see it','The page needs a visible main heading, not just a tab label.',choice('Which element makes “Welcome” the visible main heading?','h1',[['title','<title>Welcome</title>'],['h1','<h1>Welcome</h1>'],['p','<p>Welcome</p>']],'h1 is the visible main heading. title labels the tab; p is a paragraph.','Compare their jobs: tab label, visible heading, and paragraph. The requested job is visible main heading.')),
  say('Add a paragraph','A paragraph is a block of ordinary text, enclosed by <p> and </p>. Place it in body after the heading. You choose the words; the tags describe the structure.',{code:'<h1>A quiet sky</h1>\n<p>A resting place for lost stars.</p>',html:'<h1>A quiet sky</h1><p>A resting place for lost stars.</p>'}),
  ask('Write one small element','Turn the two words “Hello stars” into a paragraph. Type the opening tag, words, and closing tag. A live preview appears below; the full exercise comes next.',{type:'html',prompt:'Create a paragraph containing Hello stars.',answer:'<p>Hello stars</p>',tag:'p',content:'Hello stars',why:'The <p> opening and </p> closing tags identify a paragraph. Its words now appear as paragraph content.',wrong:'Wrap Hello stars in <p> at the start and </p> at the end. Do not put the words in title.'}),
  say('Put the pieces in the supplied document','The editor already includes <!doctype html>, html, head and body. Those form the document frame; keep them. Fill title inside head. Add h1 and p inside body. The required TAB title is exact; your visible heading and paragraph can use your own words.',{code:'<!doctype html>\n<html lang="en">\n<head>\n  <title>Pip’s notebook</title>\n</head>\n<body>\n  <h1>A quiet sky</h1>\n  <p>A resting place for lost stars.</p>\n</body>\n</html>',recap:true})
 ]},
 'web-links':{source:'WEB-01 · pp. 2, 17–18: attributes, hyperlinks and anchors. Uses the documented modern id-based adaptation, not the older self-closing anchor example.',steps:[
  say('A link has text and a destination','An element <a> makes a link. href is an attribute: extra information in the opening tag. In <a href="#harbour">Visit the harbour</a>, the words are clickable text, while #harbour is where they lead.',{code:'<a href="#harbour">Visit the harbour</a>'}),
  say('Give the destination a matching name','id="harbour" labels a destination. href="#harbour" points to that label on the same page. Use the # in href, not in id. The id identifies one destination, so do not duplicate it.',{code:'<a href="#harbour">Visit the harbour</a>\n<h2 id="harbour">Harbour</h2>',html:'<a href="#harbour">Visit the harbour</a><p>The path across the sky.</p><h2 id="harbour">Harbour</h2>'}),
  ask('Connect one end','The destination is already named sky. You only need the href value.',token('For <h2 id="sky">Sky</h2>, what goes inside href="____"?','#sky','href="#sky" points to the element with id="sky". The names match, with # only in the link.','The link needs # followed by the exact destination name: sky.')),
  ask('Fix a mismatched pair','The link says href="#moon" but the destination says id="moonlight". Those are different names.',choice('Keeping id="moonlight", which link reaches it?','#moonlight',[['#moon','#moon'],['#moonlight','#moonlight'],['moonlight','moonlight (no #)']],'#moonlight matches id="moonlight" on this page. The # introduces a same-page destination.','Compare every character of the target name. moon and moonlight are not the same label.')),
  say('Make the link worth following','Put meaningful text between <a ...> and </a>; an empty link is not useful. Put visible content at the destination too. In the experiment the requested destination name changes, so replace harbour on BOTH sides with that name.',{code:'<a href="#harbour">Visit the harbour</a>\n<h2 id="harbour">Harbour</h2>',recap:true})
 ]},
 'web-css':{source:'WEB-01 · pp. 19–24: CSS rules, class selectors, colours. Padding is an explicitly supplementary game skill, cross-checked with MDN (see source map); not claimed as covered in these lecture pages.',steps:[
  say('Separate the words from their appearance','HTML supplies the page’s content and structure. CSS supplies styling. The two editors have different jobs: write tags in HTML, and styling rules in CSS.',{code:'/* CSS example */\np { color: gold; }',html:'<p>A paper beacon.</p>',css:'p { color: gold; }'}),
  say('Read a styling rule','In .beacon { color: gold; }, .beacon is the selector: which elements to style. color is the property: what to change. gold is the value: the chosen colour. Braces enclose the declarations, a colon separates property and value, and a semicolon ends a declaration.',{code:'.beacon {\n    color: gold;\n}'}),
  say('Connect the class to its selector','In HTML, class="beacon" gives an element a class name. In CSS, .beacon selects that class. A dot means class; # means id. Multiple elements can have the same class and receive the same styling.',{code:'<!-- HTML -->\n<p class="beacon">First light</p>\n<p class="beacon">Second light</p>\n\n/* CSS */\n.beacon { color: gold; }',html:'<p class="beacon">First light</p><p class="beacon">Second light</p>',css:'.beacon { color: gold; }'}),
  ask('Choose a selector','Both paragraphs have class="signal". You want one reusable rule for both.',choice('Which selector selects that class?','.signal',[['.signal','.signal'],['#signal','#signal'],['signal','signal']],'The dot selects a class. .signal matches class="signal" on both paragraphs.','A # would select an id. A bare name would select an element type. A class selector begins with a dot.')),
  say('Give the words breathing room','Supporting game skill: padding is the space INSIDE an element, between its content and border. A single value such as padding: 12px sets all four sides. px is the CSS pixel unit. This small addition is not covered by the cited lecture pages.',{code:'.beacon {\n    color: gold;\n    padding: 12px;\n}',html:'<p class="beacon">First light</p><p class="beacon">Second light</p>',css:'.beacon { color: gold; padding:12px; border:1px solid; }'}),
  ask('Complete one declaration','You want 12 pixels of inner space on all four sides.',token('Complete padding: ____; with a number and unit.','12px','padding: 12px; gives the same inner spacing to the top, right, bottom and left.','Write the number immediately followed by the unit: 12px, with no space between 12 and px.')),
  say('Use the exact colour requested','A colour can be a name or a hexadecimal code such as #ffd166. Here # is part of a colour VALUE after color:, not an id selector. The experiment gives the class, colour code and minimum padding. Copy those requirements into the matching parts of the CSS rule.',{code:'.beacon {\n    color: #ffd166;\n    padding: 16px;\n}',recap:true})
 ]}
};
